stages:
  - test
  - build
  - deploy

realizar_testes:
  stage: test
  image: node:17-alpine3.14
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml
  only:
    - kubernetes

build_images:
  stage: build
  needs:
    - realizar_testes
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t thiago/gitlab-cicd-node:1.0 .
    - docker push thiago/gitlab-cicd-node:1.0
  only:
    - kubernetes

deploy_dev:
  stage: deploy
  needs:
    - build_images
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@35.198.57.187 <<EOF
      sudo rm -Rf *
      sudo git clone --branch kubernetes https://gitlab.com/thiago/gitlab-cicd-app-base.git
      cd gitlab-cicd-app-base
      kubectl apply -f deployment.yml
      EOF
  only:
    - kubernetes
